version: "3.8"

services:
  # Backend Service
  backend:
    build: ./backend
    restart: always
    environment:
      PORT: 3000
      DATABASE_URL: ${DATABASE_URL:-mysql://user:password@127.0.0.1:3306/pesantren}
      JWT_SECRET: ${JWT_SECRET:-rahasia_negara_api}
      CORS_ORIGINS: "*"
      VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY}
      VAPID_PRIVATE_KEY: ${VAPID_PRIVATE_KEY}
      VAPID_SUBJECT: ${VAPID_SUBJECT:-mailto:admin@minhajulhaq.com}
    volumes:
      - ./backend/uploads:/app/uploads
    network_mode: host

  # Frontend Service
  frontend:
    build: ./frontend
    restart: always
    network_mode: host
